### ISSUE TITLE
Pinball-Loss and Gradient

### ISSUE THREAD

**Issue by StatMixedML** [RektPunk/monotone-quantile-tree#1]
Thanks for translating the implementation of [Cannon (2018)](https://link.springer.com/article/10.1007/s00477-018-1573-6) into the LightGBM framework. Great effort!

I am wondering about the specific implementation of the Pinball-Loss and Gradient you are using. Can you please elaborate on this, thanks!

**Comment by RektPunk** [comment]
Of course, I used pinball loss (or tilted absolute loss) and its gradient https://github.com/RektPunk/Lightgbm-monotone-quantile/blob/d2cd9a019ed1443ad087f763ed4daa8576b23046/module/objective.py#L6-L11 just as definition (point zero is not considered). And set hessian as 1 and make lightgbm use it https://github.com/RektPunk/Lightgbm-monotone-quantile/blob/d2cd9a019ed1443ad087f763ed4daa8576b23046/module/model.py#L71-L72

I wish it would be informative answer enough. :)
